### ISSUE TITLE
License creation fails with "AssertionError: License text file must be defined."

### ISSUE THREAD

**Issue by matthias-mayr** [boschresearch/ros_license_toolkit#45]
My expectation would have been that the `-c` option would write a new license file for me if I have specified an SPDX-compliant license in the `package.xml`.  
At least in this repo it fails. Maybe I am using it wrong though:

```python
matthias@Odin:~/Workspaces/skiros_ws/src/skiros2/skiros2$ ros_license_toolkit -c .
Found 1 packages in .
====================
[skiros2]
git hash of (/home/matthias/Workspaces/skiros_ws/src/skiros2): 96cf471085babc1e3462f69e4418ddbcb96012d8
LicenseTagExistsCheck
 SUCCESS Found licenses ['LGPL-3.0-or-later']
LicenseTagIsInSpdxListCheck
 SUCCESS All license tags are in SPDX list of licenses.
LicenseTextExistsCheck
 FAILURE The following license tags do not have a valid license text file:
  'LGPL-3.0-or-later': No license text file defined.
LicensesInCodeCheck
 FAILURE AssertionError: License tag must have file attribute.
--------------------
[skiros2] Overall:
 FAILURE
====================
Traceback (most recent call last):
  File "/home/matthias/.local/bin/ros_license_toolkit", line 8, in <module>
    sys.exit(main())
  File "/home/matthias/.local/lib/python3.8/site-packages/ros_license_toolkit/main.py", line 104, in main
    package.write_copyright_file(
  File "/home/matthias/.local/lib/python3.8/site-packages/ros_license_toolkit/package.py", line 271, in write_copyright_file
    f.write(self.get_copyright_file_contents())
  File "/home/matthias/.local/lib/python3.8/site-packages/ros_license_toolkit/package.py", line 255, in get_copyright_file_contents
    assert pkg_license.license_text_file, \
AssertionError: License text file must be defined.

**Comment by ct2034** [comment]
Hey Matthias. Thanks for bringing this up. The change that I would implement in response to this is, that the copyright-file generation will not be invoked, if the linter failed. Because it is not the scope of this tool to create the license file for you. You have to make sure yourself that the repo contains the correct license in the first place.
